### ISSUE TITLE
FilePickerActivity   cannot start

### ISSUE THREAD

**Issue by 1261810499** [prscX/react-native-file-selector#15]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.newrouter/com.nbsp.materialfilepicker.ui.FilePickerActivity}: java.lang.RuntimeException: Failed to resolve attribute at index 1362
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
        at android.app.ActivityThread.access$800(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5293)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 1362

**Comment by ricbermo** [comment]
I got this working, check this https://github.com/prscX/react-native-file-selector/issues/11#issuecomment-428352128

**Comment by prscX** [comment]
Thanks @ricbermo for sharing the solution and it's reference.

Thanks
</ Pranav >
