### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by shubham-srivastava-goku** [prscX/react-native-file-selector#7]
Hi there,
I'm very new to React Native and I'm facing some issue in installing this lib.
I have installed the library and then kinked it.
After running the command react-native run-android, I am getting this error :

![image](https://user-images.githubusercontent.com/25581796/40960192-990dcfb6-68bc-11e8-8f8f-14d34c430ad2.png)

Please help me to resolve it. 
Thanks in advance.

**Comment by shubham-srivastava-goku** [comment]
I have updated gradle version, changed sdk version in android\app\build.gradle and added maven dependencies in android\build.gradle

android\app\build.gradle

android {
    compileSdkVersion 27 <-
    buildToolsVersion "27.0.3" <-

   defaultConfig {
        .......
        targetSdkVersion 27 <-

   dependencies {
       ..........
      compile 'com.android.support:appcompat-v7:27.0.2' <-
      compile 'com.android.support:support-v4:27.0.2' <-
   }

android\build.gradle
allprojects {
    repositories {
        ............
        maven {
            url  "http://dl.bintray.com/lukaville/maven"
        }
    }
}


Now the build is successful but app is crashing when I am adding file selector code. I don't know the root cause.

**Comment by prscX** [comment]
Thanks @shubham-srivastava-goku for raising the issue. Have you configured below step:

- Add below color attributes in your app res/color.xml. You can provide your own color codes
    <color name="colorPrimary">#3F51B5</color>
    <color name="colorPrimaryDark">#303F9F</color>
    <color name="colorAccent">#FF4081</color>

Thanks
</ Pranav >

**Comment by shubham-srivastava-goku** [comment]
@prscX , from where I can get this xml file. There should be a predefined file for this project I guess.

**Comment by prscX** [comment]
@shubham-srivastava-goku: Basically in your android app, you need to create a resource file `res/color.xml` if it does not exist. Please refer example app for the same.

Please let me know in case you still face the same issue.

Thanks
</ Pranav >

**Comment by jtara1** [comment]
@shubham-srivastava-goku you helped me get further in the build, but it still fails for me

```
$ react-native run-android
...
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.android.support:appcompat-v7:27.0.2.
     Searched in the following locations:
         file:/home/j/Android/Sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.2/appcompat-v7-27.0.2.pom
         file:/home/j/Android/Sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.2/appcompat-v7-27.0.2.jar
         file:/home/j/_Github-Projects/CentralComicReader/android/sdk-manager/com/android/support/appcompat-v7/27.0.2/appcompat-v7-27.0.2.jar
     Required by:
         CentralComicReader:app:unspecified
   > Could not find com.nbsp:library:1.8.
     Searched in the following locations:
         file:/home/j/Android/Sdk/extras/android/m2repository/com/nbsp/library/1.8/library-1.8.pom
         file:/home/j/Android/Sdk/extras/android/m2repository/com/nbsp/library/1.8/library-1.8.jar
         file:/home/j/_Github-Projects/CentralComicReader/android/sdk-manager/com/nbsp/library/1.8/library-1.8.jar
     Required by:
         CentralComicReader:app:unspecified > CentralComicReader:react-native-file-selector:unspecified
   > Could not find com.android.support:appcompat-v7:27.0.2.
     Searched in the following locations:
         file:/home/j/Android/Sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.2/appcompat-v7-27.0.2.pom
         file:/home/j/Android/Sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.2/appcompat-v7-27.0.2.jar
         file:/home/j/_Github-Projects/CentralComicReader/android/sdk-manager/com/android/support/appcompat-v7/27.0.2/appcompat-v7-27.0.2.jar
     Required by:
         CentralComicReader:app:unspecified > CentralComicReader:react-native-file-selector:unspecified
   > Could not find com.android.support:support-v4:27.0.2.
     Searched in the following locations:
         file:/home/j/Android/Sdk/extras/android/m2repository/com/android/support/support-v4/27.0.2/support-v4-27.0.2.pom
         file:/home/j/Android/Sdk/extras/android/m2repository/com/android/support/support-v4/27.0.2/support-v4-27.0.2.jar
         file:/home/j/_Github-Projects/CentralComicReader/android/sdk-manager/com/android/support/support-v4/27.0.2/support-v4-27.0.2.jar
     Required by:
         CentralComicReader:app:unspecified > CentralComicReader:react-native-file-selector:unspecified
   > Could not find com.android.support:appcompat-v7:27.0.2.
     Searched in the following locations:
         file:/home/j/Android/Sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.2/appcompat-v7-27.0.2.pom
         file:/home/j/Android/Sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.2/appcompat-v7-27.0.2.jar
         file:/home/j/_Github-Projects/CentralComicReader/android/sdk-manager/com/android/support/appcompat-v7/27.0.2/appcompat-v7-27.0.2.jar
     Required by:
         CentralComicReader:app:unspecified > com.facebook.react:react-native:0.55.4

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 56.024 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
```

**Comment by jtara1** [comment]
Found my solution here https://github.com/react-native-community/react-native-svg/issues/584 

had to change this line in the file `$myProject/android/gradle/wrapper/gradle-wrapper.properties` to 

`distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip` I was using gradle 2.x for whatever reason by default

Other tips for others having build issues: read through the config files (at least build.gradle and app/build.gradle) in the `Example` folder in the root of this repo

**Comment by shubham-srivastava-goku** [comment]
@jtara1 , hi, I've updated gradle version.
Now the app is building but now the runtime error is coming and app is crashing.

	FATAL EXCEPTION: main
	Process: com.fileexp, PID: 7162
	java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fileexp/com.nbsp.materialfilepicker.ui.FilePickerActivity}: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 1: TypedValue{t=0x2/d=0x7f03005f a=1240 r=0x7f050028}
	  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2875)
	  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2950)
	  at android.app.ActivityThread.-wrap11(Unknown Source:0)
	  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
	  at android.os.Handler.dispatchMessage(Handler.java:105)
	  at android.os.Looper.loop(Looper.java:164)
	  at android.app.ActivityThread.main(ActivityThread.java:6750)
	  at java.lang.reflect.Method.invoke(Native Method)
	  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
	Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 1: TypedValue{t=0x2/d=0x7f03005f a=1240 r=0x7f050028}
	  at android.content.res.TypedArray.getColor(TypedArray.java:469)
	  at android.app.Activity.onApplyThemeResource(Activity.java:4267)
	  at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:199)
	  at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:141)
	  at android.app.Activity.setTheme(Activity.java:4245)
	  at android.support.v7.app.AppCompatActivity.setTheme(AppCompatActivity.java:89)
	  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2821)
	  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2950) 
	  at android.app.ActivityThread.-wrap11(Unknown Source:0) 
	  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616) 
	  at android.os.Handler.dispatchMessage(Handler.java:105) 
	  at android.os.Looper.loop(Looper.java:164) 
	  at android.app.ActivityThread.main(ActivityThread.java:6750) 
	  at java.lang.reflect.Method.invoke(Native Method) 
	  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

Are you getting any errors after updating gradle version.

**Comment by jtara1** [comment]
@shubham-srivastava-goku I wasn't getting any runtime errors, but the entire app just crashed when I called `RNFileSelector.Show` using the example usage code. I'm guessing my issue here was that I'm using android 5.1, but this requires android API 27+ (?).

**Comment by ronastlelobo** [comment]
Same error here.

**Comment by shubham-srivastava-goku** [comment]
@ronastlelobo use react-native-document-picker. It is working fine for me.

**Comment by ronastlelobo** [comment]
I am using react-native-document-picker itself. But I am unable to get the absolute path of the file. I am getting "content://com.android.........../document./....", my expectation is "filepath://SDCARD/documents/.......". So I was testing out this library.

**Comment by shubham-srivastava-goku** [comment]
@ronastlelobo  you got any solutions ?

**Comment by ronastlelobo** [comment]
@shubham-srivastava-goku  follow this link [https://stackoverflow.com/questions/52423067/how-to-get-absolute-path-of-a-file-in-react-native/52551982#52551982](Solution for getting Absolute path using react-native-document-picker) and follow my first comment in this link of how i used it [https://github.com/Elyx0/react-native-document-picker/issues/156](Usage Example)
